namespace DSCons.Revit.Starter.Infrastructure;

/// <summary>Accent color generated by personalize-starter.ps1.</summary>
public static class UiBranding
{
    public const string PrimaryColor = StudentBranding.PrimaryColor;
}
